name: Sync From Upstream

on:
  schedule:
    - cron: "0 * * * *"   # tiap 1 jam
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork from upstream
        uses: tj-actions/sync-fork@v2
        with:
          upstream_repo: nengmaya538/nengmaya538.github.io
          upstream_branch: master
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

